local killsey = {  ---Slava rossie
-- lio
'😏made by nixus and xosmane🙄', 
"'mhm stOp PaStiNg StOrmY😡' - J.",
'xosmane one love😂', 
'😪loving wall', 
'"у вас скрипт не стреляет, идиоты🤣" - никсус',
'pups🤗' ,
'ᓚᘏᗢbbot on top', 
'flopawawr(^///^)', 
'moded penಠ_ಠ',
'1 🥳fps media', 
'roblox hvh😨', 
'"да ьука хуьисосина ты еьбаньая" - банан',
'"КОГО ТЫ БЬЛ@ТЬ П@З@ДАНУЛ" - банан',
'"😎бектрек кривой огузки" - поап',
'"😚их дядя путин на хвх еьбьать будет" - поап',
'"молодост🤩ь ь@ять была ахьуеная" - поап',
'"вот раньше на фейкдаках леон как пиьдарас сидел🪑" - поап',
'"ты чо не здох💀" - поап',
'"газпром одобряет🌌" - поап',
'"ВОТ ТЫ ПьИздьабол ь@ять" - поап',
'"сосать!" - поап🆘',
'"бананньегр" - поап',
'"слоник🥺" - поап',
'"я ем детей.. 🤡жареными" - лио',
'"пьизда tebe шлю(☞ﾟヮﾟ)☞а ты еьбьаная" - поап',
'"пьизьдаблятина" - поап🖤',
'"щя еьбьать будем" - поап🎧',
'🏪я куплю шторми и буду садить леона на кнайф - банан',
'🌍🌎🌏вот если бы небыло инвадеда и шиппи мы бы уже на другой планете были бы - банан😆',
'весел😂о',
'linoria sucks💹',
'boredddddddddddddddddddddddddddd😪',
'😏',
'1\'d😭',
'Ahhh~😍',
'vru',
'pep🎞si on top',
'🧨plug and play or die and pay',
'Hexago(┬┬﹏┬┬) de carlo',
'ta🎃ppino',
'el tappo',
'papini d😼chki',
'mamkina mogila tebya shdet💩',
'pastim pastim🍕',
's koreshami v voice➿',
'stixica j tapnet - banan🧈',
'just say others im russian🎒',
'pen fr fr🔏',
'он ПЕРЕСТАЛ стрелять - никсус👌🏿',
'бысьрей пленти🛐 пока он не сломал тебе айпи адрес',
'устал пастить🍝',
'бед америка | гуд раша🏈',
'You were 🦵kicked from this experience: Noclipping',
'👤seere user',
'🧔🏿beanbot paste fr fr',
'get real emo📖',
'i love ©🅿',
'emo boyyy👨‍👩‍👧‍👦',
'fr 11️⃣',
'ccccccccccccccccccccccccccccccccc📸',
'PON🐎',
'ME🐎GA PON',
'NE PON🚫🈵🚫',
'MEG🐎A NE PON',
'ULTRA PON🐎',
'ULTRA NE PON🐎',
'🈵havai🈵 ',
'fqfqfqegarehaerghweg🈵🈵🈵🈵🈵🈵',
'[RussianWare] - succesfully tapped!👏🏿',
'❔❓⁉❔❓stix che za pi3da❔❓⁉❔❓',
}
local nixus = {
  -- nixus
   "p100",
   "hitting big p",
   "ez kills",
   "ez wins",
   "1",
   "1'd",
   "u mad??",
   "nn dead",
   "who.ru",
   "UID issue",
   "IQ issue",
   "are you gonna inject??",
   "mad?",
   "did you even execute??",
   "gimmie ur watermelons",
   "a rat with a hdmi port is typing this",	
   "It looks like your face caught on fire and someone tried to put it out with a fork.",
   "Don't you love nature, despite what it did to you?",
   "Well, that happend.",
   "OOF",
   "Ouchies.",
   "u mad?",
   "Practice makes perfect.",
   "Did you mean to do that?",
   "Don't do that again.",
   "Bada ba ba ba, I'm lovin' it.",
   "How'd that happen?",
   "SÊ‡od Ê‡Êá´‰sÊ‡á´‰uÆƒ ÊŽonÉ¹ É¥ÇÉpË™",
   "Well, that happend.",
   "yeah ok",
   "Tip : stop made this",
   "Tip : This button doesn't relieve rage, for some reason.",
   "Tip : Don't be rage.",
   "Mada mada.",
   "VCMYXC1RiQVoUHWoKPSROQ==",
   "Hack the game",
   "Error 404 : Rage quit not found.",
   "Sweet rage bro!!",
   "Whos that behind you?",
   "Oh, So close!",
   "Nope.",
   "Undo!",
   "Is that a jojo reference?",
   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHH...",
   "Stop screwing around!",
   "useless button rite",
   "?????",
   "That wasn't the plan.",
   "???????????",
   "nice one",
   "whats 4 squared?",
   "you can get everything you want",
   "Don't lose your head.",
   "Stimulate your senses.",
   "Don't clip that.",
   "Kappa.",
   "O Wuts dis?", 
   "Try again.", 
   "Game over!",
   "Why?", 
   "Stop rage quitting",
   "Are you angry yet?",
   "I've got 99 problems, This cheat aint one",
   "Huh? What happend?",
   "Where'd you go?",
   "Don't be rage again.",
   "Did you rage quit again?",
   "Fuck off, fuck off...",
   "Hello, depression",
   "I hear your message",
   "Still don't understand",
   "I know we're hurting",
   "Drugging and doping",
   "Death by our own hands",
   "I'm sorry that I couldn't be the one",
   "The end has come",
   "Hello, my mental",
   "You think I should but",
   "I can't read your mind",
   "Admit we fuck up",
   "Our wounds are healing",
   "Some can't heal with time",
   "Cause we can't run",
   "ur my fan",
   "you cried trying to report me",
   "u has no parents Imaoo",
   "are u having a bad time?",
   "u lost to C0VVID",
   "negro",
   "so trash OMEGALUL",
   "random",
   "i know ur location LOL",
   "LLLLLLLLL",
   "clipped",
   "emo lokin stupid 12yo",
   "u trying to be me so hard",
   "you waant to sjjck my djcick",
   "clip me clipping owning u",
   "ur black",
   "stay mad",
   "You're adopted kid",
   "kill pyourself",
   "special kid",
   "get ratio'ed",
   "i can buy ur life",
   "Ð”ÐµÑ€Ð¶Ð¸ âœˆ Ð¸ Ð»ÐµÑ‚Ð¸ Ð½Ð°Ñ…ÑƒÐ¹ !",
   "Hexagon is the best!",
   "missed shot due to umm i forgor",
   "[gamesense] Missed shot due to ?",
   "game:Shutdown()",
   "pls give me hexadecimal",
   "-ur life",
   "owl hub'ed",
   "LOL 9 Y.O. KID WITH FREE HACKS!11111",
   "get resolver nn boy????????????????????????????????????????????????????",
   "???????????????????????? stop pasting meme????????????????????????????????????????",
   "????????????????  dumpware wining ?????????????????????????????",
   "??????????????????????  whu.ru? whu.ru? whu.ru? whu.ru? whu.ru? whu.ru? ????????????????????????",
   "p1000????????????????????????????????????",
   "????????????????????cuteware really p100 cuteware really p100 cuteware really p100 cuteware really p100????????????????",
   "sit nn dog????????????????????",
   "???????????? can i rec media ???????????????? stop use mega tap rage????????????????",
   "LEON X FEEL =????????????????????????????????????",
   "????????????????????????  stix bad stix bad stix bad stix bad stix bad??????????????????????????????",
}
local xosmane = {
   -- xosmane
   'ne95gr2: Я СЕБЕ ШТАНЫ НАМОЧИЛ',
   'XxMonster130xX: ТЫ МЕШАЕШЬ НОРМАЛЬНЫМ ЧЕЛАМ ЖИТЬ',
   'ne95gr2: У НЕГО ЕЩЁ СПИДРАН ВКЛЮЧЁН КИК ЕГО УЖЕ',
   'RASADATOR: аим+навотка',
   'пхITLER SISTERO??!??!?!&$&"&-;@;@',
   '"у меня не стреляет😭😭" - хосмане',
   '"э кудаа леон на гуро аьа💹ьаьаь" - бананнегр',
   'moto moto 1120',
   'gg/4NmWfzvMPx',
   'HEY WHATS SCRIPT IS THAT??',
   'RUSSIANWARE',
   'russia on top yessssss',
   'how are you',
   'gg/4NmWfzvMPx join',
   'ахаха лысый поспи',
   '1 бу рашнвар',
   'ты кстати мне co|сешь ща',
   'никсус ван лав❤️',
   '"хасманя лысый гном" - никсус',
   'овнед бу рашнвар',
   'SORRY I HURT YOUR ROBLOX EGO BUT LOOK -> 🤏 I DONT CARE', -- битчбот v2 дааа
   'Free Roblox Script Silent Aim Rapid Fire God Mode',
   'Artiljerija! Bosanac sam bekrija.',
   '😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴😴',
   '😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎😎',
   '"на на получай черный" - хосмане',
   "рашнвар беттер!",
   "донт сри май бебе герл",
   "shootware'd",
   "ay look at me",
   "try kick me",
   '"ВАТАФЬАК АР Ю ДУИНГ😡" - хосмане',
   'look12space: KICK NEFOR',
   '"а сам та наьхьуй ебьантяй😏" - банан',
   '"Я тебя агрить буду когда стоять крутить⛳ тебя на вертеле и ржать🤣" - стикс',
   '"Ты меня заеьбпл,🙁" - никсус',
   '"я тебя понял😥" - хосмане',
   '"Da, vse, nahйui vash cb, ya livaem v undertale" - никсус',
   '"ты чо суьчка сам ты петух😡😡" - никсус',
   "russianware",
   "nachos.codes",
   "m+9 kick hacker",
   "kick him he hacking",
   "stop hacking noob",
   "imagine hacking in roblox",
   "russianware on top",
   "$$$ nachos.codes $$$",
   "1'ed",
   "stop hacking!!!",
   "m+9 kick",
   "$$$$$$$$$$$",
   "russianware was here",
   "oopsie",
   "missclick'ed",
   "how to buy gun",
   "stop hacking!! its against the rules!!",
   "bro cheating to be good",
   "you dont mom",
   "stop this please",
   "поколение пауков моя тима вся в ryodan'e🕷",
   "🔥обожаю playboi carti😎😎✌ и все что с ним связано💓💓",
   "бойцовский клуб редан, задыхаешься цепями⛓",
   "Порву-За-Братву",
   "🥦 Vegan living healthy",
   "Горжусь Z 🥰🇷🇺",
   "ты думаешь что ты шаришь?🤣🤣🤣🤣🤣🤣 ахаха.",
   "Доброе времени суток ! Идёт набор в клан standoff 2 Anime Win Team ",
   "доброе время суток идет набор в клан по игре коунтер блокс",
   "Роблокс игра сиреноголовий💓",
   "комфортный чатик для тебя по роблоксу",
   "Господи, как же хочется украиночку... ",
   "👏👏👍👍👍👍КЛАСС!!!!!😁😁😁",
   "На вечер для вас эта потрясная красотка с клевыми формами 😻",
   "💥💥💥Любители по фигачить клубами пара☁️",
   "Мяу! Я милая кошкодевочка. У меня пушистое меховое пальто насыщенного цвета.",
   "🤯Видео нe для слабонервных!",
   "а здесь дают робуксы?",
   "прицел пропал, как включит?",
    "Стримснайпят  Лагает ✅  Вебка пересвечивает ✅  Начали за T ✅  Не повезло ✅  0 помощи  -98хп ✅  Достал нож не в тайминг ✅  Неудобно сидеть ✅ ",
    "um guys, how do i play this game", "which button is it to shoot now", "please go easy on me guys, im new to this", "if u do not go easy on me, i will report u", -- pf.lol даа
    "M9 bayonet cool knife donater 2000 ultra super",
    "петух доллар доллар петух",
    "п-папочка, я твой котёнок 🥺",
    "пошли в войс чудо в перьях",
    "ROBLOX COUNTER STRIKE GLOBALO BLOX NEW 2024",
    "Ддос - бан навсегда без разбора 💻🚫",
    "Me: A bad and manipulative anime boy who can and will control you",
    "униженный инвалид ты мне в ширинку дышишь",
    "нюхай пэнсел,баклан",
    "не снимай подгузник, просто отодвинь его в сторону",
    "промолчишь?",
    "прилоскал косматого ~(˘▾˘~)",
    "ботик, ты про RussianWare слыхал чето?",
    "What? RussianWare? No Im using stormy-fixed",
    "senpai~~~, заовни меня ^^",
    "You Has been RAC Banned",
    "hitpart bans me😣",
    "очередной легитный еьблак",
    "buy russianware",
    "ты сочный за тебя в чат чит пишет",
    "ДА НЕ ПИКАЙ СИДИ НА МЕСТЕ",
}
local csgo = {
   -- acidtech neverlose
   "что ты сделал",
   "?",
   "найс мув",
   "пьиьздец ты конч",
   "найс подловил",
   "без дт не может",
   "просто +в",
   "на подпике",
   "еле убил",
   "почти хорошо",
   "оправдай мув",
   "ну",
   "gbpltw",
   ",kznm",
   "тупой",
   "МЕНЯ ТПХНУЛО",
   "я стрельнул?",
   "яя в муте?",
   "ну тиммейт федука давит",
   "кердык",
   "что за вонь убила",
   "ты дт отжал?",
   "у меня одново серв лаг?",
   "найс автопик+миндмг",
   "бекшут?",
   "ты с соткой встал?",
   "ну ты зверь",
   "сидит предиктит",
   "онли боди чьурка",
   "не потей",
   "ты с миндамагом пикнул?",
   "у тебя пинк спайк?",
   "как ты дамаг выбил?",
   "ну фристендинг же не сработает",
   "чит делеит",
   "ну нет",
   "сразу видно iq 14к юида",
   "S[DF[F[DF[SDF[SD[FSD[FDS[F[F[F[F",
   -- sleepcord nixware
   "1 dog",
   "1",
   "я сплю",
   "никсвар топ",
   "ребятки sleepcord на никс качаем, топ луашка!",
   "фуууу ботек ИЗИЧКА фууууу",
   "я поспал и хс'аю тебя",
   "не плачь",
   "neverlose user fell to nix|ware with sl|eepcord",
   "что то ты падаешь много",
   "в консоли miss, а в голове пусто",
   "униженный инвалид ты мне в ширинку дышишь"
}
local china = {
           -- japanese
           "武器 esp aimbot 的最佳腳本",
           "損壞修改器崩潰服務器後門專業版roll angle 免費作弊未付費",
           "新的最佳付費腳本破解繞過方法速度",
           "利用飛行模式上帝模式眼鏡未檢測到的軟件",
           "大頭不付費教程 100% 私人 xp hack",
           "工作程序 hack bunny hop 免費不付費 哈哈",
           "hitbox extender源垃圾郵件聊天惡意軟件",
           "武器免費黑客瞄準船和牆壁黑客無限彈藥上帝模式",
           "作弊 ai 模式支付最佳腳本開發者 hack",
           "釋放拖釣作弊瞄準機器人無聲破解無限跳躍",
           "免費作弊利用武器 roblox 遊戲 xray 無剪輯",
           "神速作弊武器 ro blocks 所有槍支解鎖器",
           "bunny hop cheat破解2023方法免費源碼",
           "史萊姆城堡破壞者免費欺騙破解 minecraft 破解",
           "免費作弊模式銅色類別創意破解繞過esp",
           "誰騙你玩不了哈哈喵喵破解版",
           "停止作弊哈哈我是合法的職業球瞄準船牆黑客",
           "免費破解我的專業作弊 aimbot wallhack 不付費變壞",
           "大頭預測漏洞利用方法免費繞過破解",
           "你是怎麼得到這個的請回答 fake lag",
           "印度尼西亞使用 hacking 免費作弊 ",
           "兔子跳自動牆技巧 lifehack 禁令繞過",
           "免費手榴彈繞過作弊工作 roblox aimbot 瞄準無聲目標繞過 2023 工作真正免費下載和使用",
           "你好青蟲我討厭你傻媽媽傻媽媽青蟲",
           "抱著毀滅性的神經沉重的繁榮遊行臉紅青銅類創意案例",
           "此服務器上的開發者請幫助我免費且非常易於使用的手榴彈 2023 繞過",
           "去觸摸草地哈哈遊戲椅哈哈太有趣了我瘋了我笑得太厲害了",
           "踢他請按F1兄弟為什麼你不踢他哈哈去觸摸黑客",
           "垃圾郵件這麼難容易破解免費粘貼 bin 繞過",
           "水晶創意玻璃頭眼睛喵喵貓狗鸚鵡手隨機文字芝士漢堡怎麼做",
           "破解菜單解鎖所有槍支付費方法無限彈藥",
           "擁有最好的作弊容易哭更多沒有名字哈哈",
           "因黑客攻擊而被禁止武器開發者哭得很厲害",
           "讓生活更輕鬆的生活小竅門只需洗碗便便便可獲利",
           "隨機文本是的為什麼你讀這個我是中國人我發誓我沒有使用翻譯器",
           "被最好的騙子控制大聲笑哭我的朋友擁有踢被撞毀",
           "俄羅斯穿頂盤灰色塊兩塊立體聲揚聲器你好隨機文本",
}
local random = {
           -- random text
           "cheat code hvh anti aim legit hack trickshot maker",
           "no virus mediafire link exploit hitting p debug menu",
           "teleport not paid hack meme all clean",
           "server backdoor cookie logger chams aim bot",
           "big head rapid fire cheat op verified",
           "hitbox extender source spam chat malware",
           "cheat crack tp hack method free esp",
           "no ban bypass download desync not leaked",
           "kill all hacks no leaked silent aim hacks",
           "fly mode script gun hack no clip tutorial",
           "esp no anti-cheat detect for free no linkvertise",
           "exploit hack free damage modifier free btools",
           "undetected full 100% free private hack unlimited wallbang",
           "cb free hack aim boat and wall hack infinite ammo god mode",
           "roblox mod menu with hack super jump fly",
           "god speed cheat cbro roblox all gun unlocker",
           "software free sniper gun hack trolling owns all program",
           "free cheat exploit cb roblox games xray no clip",
           "working program hack esp chams bunny hop xp hack",
           "cheating ai mode paid best script developers hack",
           "bypass anti-cheat fire rate speed cheat",
           "infinite damage for free encrypted cracked roblox",
           "release trolling cheat aim bot silent crack infinite jump",
           "speed cheat troll pause game cb desync",
           "big head not paid tutorial 100% private xp hack",
}
local facts = {
           -- facts (ru)
           "Несмотря на все свое население, в китае используется всего около 200 фамилий.",
           "Существует растение, которое называют цветком смеха. Оно вызывает беспричинный смех на полчаса.",
           "Люди с голубыми глазами лучше видят в темноте.",
           "Среднестатистическая женщина за свою жизнь успевает посидеть на 32 диетах.",
           "Самый старый обнаруженный рецепт супа датируется 6000 годом до нашей эры. Главный ингредиент — мясо бегемота.",
           "Жирафы в целях самозащиты действуют головой как молотком.",
           "В Швейцарии выпустили детские презервативы.",
           "Чихание при взгляде на солнце — это аутосомно-доминантный непроизвольный гелио-глазной синдром взрыва.",
           "Потребление йогурта в мире возросло за последние 12 лет в четыре раза.",
           "На территории Японии 17 действующих вулканов.",
           "В Саудовской Аравии нет ни одной реки.",
           "Как минимум три часа в день мы бездельничаем.",
           "В большинстве реклам время показываемое на часах – 10:10, чтобы не закрывать марку часов.",
           "Имя шейха Хамада написано на Земле километровыми буквами и видно из космоса.",
           "В Албании кивание головой значит «нет», и наоборот.",
           "В Алабаме запрещено водить машину необутым. Закон, однако, позволяет ездить по встречной полосе, если включить фары.",
           "Комары могут летать во время дождя.",
           "У человека меньше мyскyлов, чем y гyсеницы.",
           "Браки, в которых жены плохо спят, имеют гораздо больше шансов развалиться.",
           "При сильной рвоте у человека могут лопнуть сосуды в глазах.",
           "За пол века овощи стали менее полезны.",
           "Япония — последняя страна в мире, формально сохранившая титул Империи.",
           "Бильярд, так же как и шахматы, имеет очень древнее происхождение, а его родиной является Азия.",
           "В Антарктиде банкоматов в 2 раза больше, чем постоянных жителей.",
           "Пизанская башня никогда не была прямой!",
           "Полярная крачка — единственная птица, которая мигрирует с одного полюса на другой.",
           "Самые большие в мире сластены - немцы и швeйцарцы: Cогласно статистике, в год каждый из них съедает по 10-11 кг шоколада.",
           "Каждый американец имеет, в среднем, 7 пар джинсов.",
           "Самая распространенная скальная порода на земле — это базальт.",
           "ДНК человека и банана совпадают на 50%.",
           "При ярком свете человек съедает намного меньше, чем с приглушённым тусклым освещением.",
           "Горькие напитки делают людей критичнее и строже.",
           "Гречка очищает желудок от жвачек.",
           "Лечебные свойства зелёного чая — это миф",
           "Лингвисты утверждают, что в любом языке есть слово, обозначающее подхалима.",
           "Длина самого длинного лимузина в мире — 30,5 метров",
           "На холоде насекомые дрожат, как и человек.",
           "Змея может спать в течение 3 лет.",
           "На Гавайях серфинг включен в школьную программу.",
           "В Швейцарии запрещено смывать воду в туалете после 10 часов вечера.",
           "Стрекозы в буквальном смысле до смерти боятся рыб.",
           "Женские сердца бьются быстрее, чем у мужчин.",
           "Три силовых занятия в неделю дают наибольший эффект.",
           "Каучук – один из ингредиентов жевательной резинки. Благодаря ему мы можем надувать пузыри.",
           "Аисты могут засыпать в полете на 10-15 минут.",
           "По статистике 66% людей закрывают глаза во время поцелуя.",
           "Виадук Мийо - самый высокий мост в мире!",
           "В центре Мадрида есть отель из мусора.",
           "Пчелы никогда не спят. Пчела замирает на соте лишь на несколько секунд в течение суток.",
           "Пожилых людей больше всего в Швеции (24%) и меньше всего в Кувейте (2%).",
           "Булемия - это неукротимый аппетит.",
           "Лысых людей не выгоняют из церкви, потому что гонять лысого - грех.","Чаще всего, самые тихие люди - немые.","Если долго смотреть на огонь, то тебя уволят из МЧС.","Не покупай вентиляторы - это деньги на ветер.","Девушки как кредит, кому-то дают, а кому-то нет.","Что не так с рестораном на Луне? Блюда изысканные, но нет атмосферы.","Горчицу знаешь? Я огорчил.","Когда говоришь, что думаешь , думай что говоришь.","Проблем по жизни будет много, но выбор за нами. Либо ныть, либо попу мыть.","Каждый может кинуть камень в волка , но не каждый может кинуть волка в камень.",
}
